name: 'retailpulse_dbt'
version: '1.0.0'
config-version: 2

profile: 'retailpulse_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  retailpulse_dbt:
    staging:
      +schema: retailpulse_silver
      +materialized: view
    intermediate:
      +schema: retailpulse_silver
      +materialized: view
    marts:
      +schema: retailpulse_gold
      +materialized: table
